#pragma once
#include "dtp.hpp"
#include <sstream>
#include <unordered_set>
#include <algorithm>

namespace dtp {

// Emits portable C99 code — then GCC/Clang applies full -O3 optimization.
// This gives us: auto-vectorization, inlining, register allocation, LTO, PGO.
// Result: DTP code performs on par with hand-tuned C.

class CodeGen {
public:
    std::vector<Diagnostic> diagnostics;

    std::string generate(const Module& mod) {
        emit_header();
        // 1) Struct/enum forward tag declarations
        for (auto& item : mod.items) {
            if (auto* s = dynamic_cast<const StructDecl*>(item.get()))
                out_ << "typedef struct " << s->name << " " << s->name << ";\n";
            if (auto* e = dynamic_cast<const EnumDecl*>(item.get()))
                out_ << "typedef enum " << e->name << " " << e->name << ";\n";
        }
        out_ << "\n";
        // 2) Struct/enum full definitions
        for (auto& item : mod.items) {
            if (auto* s = dynamic_cast<const StructDecl*>(item.get())) gen_struct(s);
            if (auto* e = dynamic_cast<const EnumDecl*>(item.get()))   gen_enum(e);
        }
        // 3) Function forward declarations
        for (auto& item : mod.items) {
            if (auto* fn = dynamic_cast<const FnDecl*>(item.get())) {
                if (!fn->body) continue;
                emit_fn_decl(fn);
            }
        }
        out_ << "\n";
        // 4) Function definitions (skip structs/enums already done)
        for (auto& item : mod.items) {
            if (dynamic_cast<const StructDecl*>(item.get())) continue;
            if (dynamic_cast<const EnumDecl*>(item.get()))   continue;
            gen_top(item.get());
        }
        return out_.str();
    }

private:
    std::ostringstream out_;
    int indent_ = 0;
    int label_cnt_ = 0;
    std::unordered_map<std::string,int> struct_sizes_;
    std::vector<std::string> defer_stack_;

    std::string fresh_label() {
        return "__dtp_l" + std::to_string(label_cnt_++);
    }

    void ind() { for(int i=0;i<indent_;i++) out_ << "  "; }
    void line(const std::string& s) { ind(); out_ << s << "\n"; }

    void emit_header() {
        out_ << "// Generated by DTP compiler\n";
        out_ << "// DTP — Direct Transfer Protocol Language\n\n";
        out_ << "#include <stdint.h>\n";
        out_ << "#include <inttypes.h>\n";
        out_ << "#include <stdbool.h>\n";
        out_ << "#include <stddef.h>\n";
        out_ << "#include <string.h>\n";
        out_ << "#include <stdlib.h>\n";
        out_ << "#include <stdio.h>\n";
        out_ << "#include <math.h>\n\n";

        // Type aliases
        out_ << "typedef int8_t   i8;\n";
        out_ << "typedef int16_t  i16;\n";
        out_ << "typedef int32_t  i32;\n";
        out_ << "typedef int64_t  i64;\n";
        out_ << "typedef uint8_t  u8;\n";
        out_ << "typedef uint16_t u16;\n";
        out_ << "typedef uint32_t u32;\n";
        out_ << "typedef uint64_t u64;\n";
        out_ << "typedef float    f32;\n";
        out_ << "typedef double   f64;\n";
        out_ << "typedef char     dtp_char;\n\n";

        // Slice type
        out_ << "typedef struct { void* ptr; u64 len; u64 cap; } __dtp_slice;\n\n";

        // Built-in macros
        out_ << "#define DTP_LIKELY(x)   __builtin_expect(!!(x),1)\n";
        out_ << "#define DTP_UNLIKELY(x) __builtin_expect(!!(x),0)\n";
        out_ << "#define DTP_INLINE      __attribute__((always_inline)) inline\n";
        out_ << "#define DTP_NOINLINE    __attribute__((noinline))\n";
        out_ << "#define DTP_RESTRICT    __restrict__\n";
        out_ << "#define DTP_PURE        __attribute__((pure))\n";
        out_ << "#define DTP_HOT         __attribute__((hot))\n";
        out_ << "#define DTP_COLD        __attribute__((cold))\n\n";

        // Built-in functions
        out_ << "// --- Built-ins ---\n";
        out_ << "static DTP_INLINE void __dtp_print_i64(i64 v){ printf(\"%lld\", (long long)v); }\n";
        out_ << "static DTP_INLINE void __dtp_print_u64(u64 v){ printf(\"%llu\", (unsigned long long)v); }\n";
        out_ << "static DTP_INLINE void __dtp_print_f64(f64 v){ printf(\"%g\", v); }\n";
        out_ << "static DTP_INLINE void __dtp_print_str(const char* s){ fputs(s,stdout); }\n";
        out_ << "static DTP_INLINE void __dtp_print_bool(bool v){ fputs(v?\"true\":\"false\",stdout); }\n";
        out_ << "static DTP_INLINE void __dtp_print_char(char c){ putchar(c); }\n";
        out_ << "static DTP_INLINE void __dtp_println(){ putchar('\\n'); }\n\n";

        // Memory
        out_ << "static DTP_INLINE void* __dtp_alloc(u64 sz){\n";
        out_ << "  void* p=malloc((size_t)sz); if(!p){fputs(\"OOM\\n\",stderr);exit(1);} return p;\n}\n";
        out_ << "static DTP_INLINE void __dtp_free(void* p){ free(p); }\n\n";

        // Input builtins
        out_ << "static DTP_INLINE void __dtp_flush_stdin(void){\n";
        out_ << "  int c; while((c=getchar())!='\\n'&&c!=EOF){}\n}\n";
        out_ << "static DTP_INLINE i64 __dtp_read_i64(void){\n";
        out_ << "  i64 v=0; scanf(\"%lld\",&v); __dtp_flush_stdin(); return v;\n}\n";
        out_ << "static DTP_INLINE f64 __dtp_read_f64(void){\n";
        out_ << "  f64 v=0.0; scanf(\"%lf\",&v); __dtp_flush_stdin(); return v;\n}\n";
        out_ << "static char __dtp_read_buf[4096];\n";
        out_ << "static DTP_INLINE const char* __dtp_read_str(void){\n";
        out_ << "  if(fgets(__dtp_read_buf,sizeof(__dtp_read_buf),stdin)){\n";
        out_ << "    size_t l=strlen(__dtp_read_buf);\n";
        out_ << "    if(l>0&&__dtp_read_buf[l-1]=='\\n') __dtp_read_buf[l-1]='\\0';\n";
        out_ << "  } else { __dtp_read_buf[0]='\\0'; }\n";
        out_ << "  return __dtp_read_buf;\n}\n";
        out_ << "static DTP_INLINE bool __dtp_read_bool(void){\n";
        out_ << "  char tmp[8]={0}; scanf(\"%7s\",tmp);\n";
        out_ << "  return (tmp[0]=='t'||tmp[0]=='1'||tmp[0]=='y');\n}\n\n";
    }

    void emit_fn_decl(const FnDecl* fn) {
        out_ << gen_type(fn->ret_type.get()) << " " << fn->name << "(";
        for (size_t i=0;i<fn->params.size();i++){
            auto& p = fn->params[i];
            out_ << gen_type(p.type.get()) << " " << sanitize(p.name);
            if (i+1<fn->params.size()) out_ << ", ";
        }
        out_ << ");\n";
    }

    std::string sanitize(const std::string& name) {
        // avoid C reserved words
        static const std::unordered_set<std::string> reserved = {
            "int","long","short","char","float","double","void","auto","register",
            "static","extern","const","volatile","signed","unsigned","struct","union",
            "enum","typedef","sizeof","return","if","else","while","for","do","break",
            "continue","goto","switch","case","default","inline","restrict"
        };
        if (reserved.count(name)) return "__dtp_" + name;
        return name;
    }

    std::string gen_type(const TypeInfo* ty) {
        if (!ty) return "void";
        switch(ty->base) {
            case BaseType::I8:    return "i8";
            case BaseType::I16:   return "i16";
            case BaseType::I32:   return "i32";
            case BaseType::I64:   return "i64";
            case BaseType::U8:    return "u8";
            case BaseType::U16:   return "u16";
            case BaseType::U32:   return "u32";
            case BaseType::U64:   return "u64";
            case BaseType::F32:   return "f32";
            case BaseType::F64:   return "f64";
            case BaseType::Bool:  return "bool";
            case BaseType::Char:  return "dtp_char";
            case BaseType::Void:  return "void";
            case BaseType::Str:   return "const char*";
            case BaseType::Ptr:
                if (ty->inner) return gen_type(ty->inner.get()) + "*";
                return "void*";
            case BaseType::RawPtr: return "void*";
            case BaseType::Array:
                if (ty->inner) return gen_type(ty->inner.get());
                return "void*";
            case BaseType::Slice: return "__dtp_slice";
            case BaseType::Struct:
            case BaseType::Enum:
                return ty->name.empty() ? "void" : ty->name;
            default: return "void";
        }
    }

    void gen_top(const ASTNode* node) {
        if (auto* fn = dynamic_cast<const FnDecl*>(node)) gen_fn(fn);
        else if (auto* st = dynamic_cast<const StructDecl*>(node)) gen_struct(st);
        else if (auto* en = dynamic_cast<const EnumDecl*>(node))   gen_enum(en);
        else if (auto* im = dynamic_cast<const ImplBlock*>(node))  gen_impl(im);
        else if (auto* us = dynamic_cast<const UseDecl*>(node)) {
            out_ << "// use ";
            for(auto& p:us->path) out_<<p<<"::";
            out_ << "\n";
        }
    }

    void gen_struct(const StructDecl* st) {
        out_ << "typedef struct " << st->name << " {\n";
        for (auto& f : st->fields) {
            out_ << "  " << gen_type(f.type.get());
            if (f.type && f.type->base == BaseType::Array && f.type->array_len > 0) {
                out_ << " " << f.name << "[" << f.type->array_len << "]";
            } else {
                out_ << " " << f.name;
            }
            out_ << ";\n";
        }
        out_ << "} " << st->name << ";\n\n";
    }

    void gen_enum(const EnumDecl* en) {
        out_ << "typedef enum {\n";
        for (auto& v : en->variants) {
            out_ << "  " << en->name << "_" << v.name;
            if (v.discriminant >= 0) out_ << " = " << v.discriminant;
            out_ << ",\n";
        }
        out_ << "} " << en->name << ";\n\n";
    }

    void gen_impl(const ImplBlock* im) {
        for (auto& m : im->methods) {
            if (auto* fn = dynamic_cast<const FnDecl*>(m.get())) {
                gen_fn(fn, im->type_name + "__");
            }
        }
    }

    void gen_fn(const FnDecl* fn, const std::string& prefix = "") {
        // Attributes
        if (fn->is_inline) out_ << "DTP_INLINE ";
        if (fn->is_ext) {
            out_ << "extern " << gen_type(fn->ret_type.get())
                 << " " << fn->name << "(";
            for (size_t i=0;i<fn->params.size();i++){
                auto& p = fn->params[i];
                out_ << gen_type(p.type.get()) << " " << sanitize(p.name);
                if (i+1<fn->params.size()) out_ << ", ";
            }
            out_ << ");\n\n";
            return;
        }

        // Return type
        out_ << gen_type(fn->ret_type.get());
        out_ << " " << prefix << fn->name << "(";
        for (size_t i=0;i<fn->params.size();i++){
            auto& p = fn->params[i];
            out_ << gen_type(p.type.get()) << " " << sanitize(p.name);
            if (i+1<fn->params.size()) out_ << ", ";
        }
        out_ << ")";

        if (!fn->body) { out_ << ";\n\n"; return; }
        out_ << " {\n";
        indent_++;

        defer_stack_.clear();
        gen_block(dynamic_cast<const BlockExpr*>(fn->body.get()), /*toplevel=*/true);

        // Emit deferred calls in reverse
        for (int i=(int)defer_stack_.size()-1;i>=0;i--) {
            line(defer_stack_[i] + ";");
        }
        defer_stack_.clear();

        indent_--;
        out_ << "}\n\n";
    }

    void gen_block(const BlockExpr* blk, bool toplevel=false) {
        if (!blk) return;
        if (!toplevel) { ind(); out_ << "{\n"; indent_++; }
        for (auto& s : blk->stmts) gen_stmt(s.get());
        if (blk->tail_expr) {
            ind();
            if (blk->tail_expr->type &&
                blk->tail_expr->type->base != BaseType::Void)
                out_ << "return ";
            out_ << gen_expr(blk->tail_expr.get()) << ";\n";
        }
        if (!toplevel) { indent_--; ind(); out_ << "}\n"; }
    }

    void gen_stmt(const ASTNode* node) {
        if (auto* s = dynamic_cast<const LetStmt*>(node)) {
            ind();
            if (!s->is_mut) out_ << "const ";
            std::string tystr = s->type_ann ? gen_type(s->type_ann.get())
                              : (s->init ? infer_c_type(s->init.get()) : "i64");

            // Array special case
            if (s->type_ann && s->type_ann->base == BaseType::Array &&
                s->type_ann->array_len > 0) {
                out_ << gen_type(s->type_ann->inner.get()) << " "
                     << sanitize(s->name) << "[" << s->type_ann->array_len << "]";
                if (s->init) out_ << " = " << gen_expr(s->init.get());
            } else {
                out_ << tystr << " " << sanitize(s->name);
                if (s->init) out_ << " = " << gen_expr(s->init.get());
            }
            out_ << ";\n";
        }
        else if (auto* s = dynamic_cast<const AssignStmt*>(node)) {
            ind();
            out_ << gen_expr(s->lhs.get()) << " " << s->op << " "
                 << gen_expr(s->rhs.get()) << ";\n";
        }
        else if (auto* s = dynamic_cast<const RetStmt*>(node)) {
            // Flush defers
            for (int i=(int)defer_stack_.size()-1;i>=0;i--)
                line(defer_stack_[i] + ";");
            ind();
            if (s->value) out_ << "return " << gen_expr(s->value.get()) << ";\n";
            else          out_ << "return;\n";
        }
        else if (auto* s = dynamic_cast<const BreakStmt*>(node)) {
            line("break;");
        }
        else if (dynamic_cast<const NextStmt*>(node)) {
            line("continue;");
        }
        else if (auto* s = dynamic_cast<const WhileStmt*>(node)) {
            ind(); out_ << "while (" << gen_expr(s->cond.get()) << ") ";
            gen_block(dynamic_cast<const BlockExpr*>(s->body.get()));
        }
        else if (auto* s = dynamic_cast<const LoopStmt*>(node)) {
            ind(); out_ << "for(;;) ";
            gen_block(dynamic_cast<const BlockExpr*>(s->body.get()));
        }
        else if (auto* s = dynamic_cast<const ForStmt*>(node)) {
            // Range-based for
            if (auto* r = dynamic_cast<const RangeExpr*>(s->iter.get())) {
                std::string start = gen_expr(r->start.get());
                std::string end   = gen_expr(r->end.get());
                std::string cmp   = r->inclusive ? "<=" : "<";
                ind(); out_ << "for (i64 " << sanitize(s->var) << " = " << start
                            << "; " << sanitize(s->var) << " " << cmp << " " << end
                            << "; " << sanitize(s->var) << "++) ";
                gen_block(dynamic_cast<const BlockExpr*>(s->body.get()));
            } else {
                // Generic iterator
                ind(); out_ << "{ __dtp_slice __iter = " << gen_expr(s->iter.get()) << ";\n";
                indent_++;
                ind(); out_ << "for (u64 __i=0; __i < __iter.len; __i++) {\n";
                indent_++;
                // var = iter[i] — need element type, use void* cast for now
                ind(); out_ << "// " << sanitize(s->var) << " = (elem)__iter.ptr[__i];\n";
                gen_block(dynamic_cast<const BlockExpr*>(s->body.get()), true);
                indent_--; ind(); out_ << "}\n";
                indent_--; ind(); out_ << "}\n";
            }
        }
        else if (auto* s = dynamic_cast<const IfExpr*>(node)) {
            ind(); out_ << "if (" << gen_expr(s->cond.get()) << ") ";
            gen_block(dynamic_cast<const BlockExpr*>(s->then_block.get()));
            for (auto& [c,b] : s->elif_branches) {
                ind(); out_ << "else if (" << gen_expr(c.get()) << ") ";
                gen_block(dynamic_cast<const BlockExpr*>(b.get()));
            }
            if (s->else_block) {
                ind(); out_ << "else ";
                gen_block(dynamic_cast<const BlockExpr*>(s->else_block.get()));
            }
        }
        else if (auto* s = dynamic_cast<const DeferStmt*>(node)) {
            defer_stack_.push_back(gen_expr(s->expr.get()));
        }
        else if (auto* s = dynamic_cast<const DropStmt*>(node)) {
            line("__dtp_free((void*)(" + gen_expr(s->expr.get()) + "));");
        }
        else if (auto* s = dynamic_cast<const ExprStmt*>(node)) {
            gen_expr_stmt(s->expr.get());
        }
        else if (auto* s = dynamic_cast<const BlockExpr*>(node)) {
            gen_block(s);
        }
    }

    void gen_expr_stmt(const ASTNode* n) {
        // Special handling for print/println
        if (auto* call = dynamic_cast<const CallExpr*>(n)) {
            if (auto* id = dynamic_cast<const IdentExpr*>(call->callee.get())) {
                if (id->name == "println" || id->name == "print" || id->name == "eprint") {
                    gen_print_call(call, id->name == "println", id->name == "eprint");
                    return;
                }
            }
        }
        ind(); out_ << gen_expr(n) << ";\n";
    }

    void gen_print_call(const CallExpr* call, bool newline, bool err_) {
        for (auto& arg : call->args) {
            ind();
            auto ty = arg->type;
            std::string expr = gen_expr(arg.get());
            if (!ty) {
                out_ << "__dtp_print_str(" << expr << ");\n";
                continue;
            }
            std::string fn;
            switch(ty->base) {
                case BaseType::I8:  case BaseType::I16:
                case BaseType::I32: case BaseType::I64: fn="__dtp_print_i64"; break;
                case BaseType::U8:  case BaseType::U16:
                case BaseType::U32: case BaseType::U64: fn="__dtp_print_u64"; break;
                case BaseType::F32: case BaseType::F64: fn="__dtp_print_f64"; break;
                case BaseType::Bool: fn="__dtp_print_bool"; break;
                case BaseType::Char: fn="__dtp_print_char"; break;
                default: fn="__dtp_print_str"; break;
            }
            out_ << fn << "(";
            // Cast for smaller ints
            if (ty->base==BaseType::I8||ty->base==BaseType::I16||ty->base==BaseType::I32)
                out_ << "(i64)(" << expr << ")";
            else if(ty->base==BaseType::U8||ty->base==BaseType::U16||ty->base==BaseType::U32)
                out_ << "(u64)(" << expr << ")";
            else if(ty->base==BaseType::Str)
                out_ << expr;
            else if(ty->base==BaseType::F32)
                out_ << "(f64)(" << expr << ")";
            else
                out_ << expr;
            out_ << ");\n";
        }
        if (newline) line("__dtp_println();");
    }

    std::string gen_expr(const ASTNode* node) {
        if (!node) return "0";

        if (auto* n = dynamic_cast<const LitIntExpr*>(node))
            return std::to_string(n->value) + "LL";
        if (auto* n = dynamic_cast<const LitFloatExpr*>(node)) {
            std::ostringstream ss; ss << n->value;
            std::string s = ss.str();
            if (s.find('.')==std::string::npos && s.find('e')==std::string::npos) s+=".0";
            return s;
        }
        if (auto* n = dynamic_cast<const LitStrExpr*>(node)) {
            std::string r = "\"";
            for (char c : n->value) {
                if (c=='\n') r+="\\n";
                else if(c=='\t') r+="\\t";
                else if(c=='\\') r+="\\\\";
                else if(c=='"') r+="\\\"";
                else r+=c;
            }
            return r + "\"";
        }
        if (auto* n = dynamic_cast<const LitCharExpr*>(node)) {
            if (n->value=='\n') return "'\\n'";
            if (n->value=='\\') return "'\\\\'";
            if (n->value=='\'') return "'\\''";
            return std::string("'") + n->value + "'";
        }
        if (auto* n = dynamic_cast<const LitBoolExpr*>(node))
            return n->value ? "true" : "false";
        if (dynamic_cast<const NullExpr*>(node)) return "NULL";

        if (auto* n = dynamic_cast<const IdentExpr*>(node))
            return sanitize(n->name);

        if (auto* n = dynamic_cast<const BinopExpr*>(node)) {
            std::string lhs = gen_expr(n->lhs.get());
            std::string rhs = gen_expr(n->rhs.get());
            std::string op = n->op;
            if (op=="and") op="&&";
            if (op=="or")  op="||";
            return "(" + lhs + " " + op + " " + rhs + ")";
        }

        if (auto* n = dynamic_cast<const UnopExpr*>(node)) {
            std::string op = n->op;
            if (op=="not") op="!";
            return "(" + op + gen_expr(n->operand.get()) + ")";
        }

        if (auto* n = dynamic_cast<const CallExpr*>(node)) {
            // Built-in len/cap/input
            if (auto* id = dynamic_cast<const IdentExpr*>(n->callee.get())) {
                if (id->name=="len" && !n->args.empty())
                    return "(((__dtp_slice)" + gen_expr(n->args[0].get()) + ").len)";
                if (id->name=="cap" && !n->args.empty())
                    return "(((__dtp_slice)" + gen_expr(n->args[0].get()) + ").cap)";
                if (id->name=="sizeof" && !n->args.empty())
                    return "(sizeof(" + gen_expr(n->args[0].get()) + "))";
                // input builtins
                if (id->name=="read_i64"   || id->name=="input_i64")   return "__dtp_read_i64()";
                if (id->name=="read_f64"   || id->name=="input_f64")   return "__dtp_read_f64()";
                if (id->name=="read_str"   || id->name=="input_str"
                    || id->name=="input")                               return "__dtp_read_str()";
                if (id->name=="read_bool"  || id->name=="input_bool")  return "__dtp_read_bool()";
            }
            std::string s = gen_expr(n->callee.get()) + "(";
            for (size_t i=0;i<n->args.size();i++){
                s += gen_expr(n->args[i].get());
                if (i+1<n->args.size()) s+=", ";
            }
            return s + ")";
        }

        if (auto* n = dynamic_cast<const IndexExpr*>(node))
            return gen_expr(n->obj.get()) + "[" + gen_expr(n->index.get()) + "]";

        if (auto* n = dynamic_cast<const FieldExpr*>(node)) {
            if (n->deref) return gen_expr(n->obj.get()) + "->" + n->field;
            return gen_expr(n->obj.get()) + "." + n->field;
        }

        if (auto* n = dynamic_cast<const CastExpr*>(node))
            return "((" + gen_type(n->target.get()) + ")(" + gen_expr(n->expr.get()) + "))";

        if (auto* n = dynamic_cast<const AddrOfExpr*>(node))
            return "(&(" + gen_expr(n->expr.get()) + "))";

        if (auto* n = dynamic_cast<const DerefExpr*>(node))
            return "(*(" + gen_expr(n->expr.get()) + "))";

        if (auto* n = dynamic_cast<const SizeofExpr*>(node))
            return "sizeof(" + gen_type(n->target.get()) + ")";

        if (auto* n = dynamic_cast<const NewExpr*>(node)) {
            std::string ty = gen_type(n->target.get());
            return "(" + ty + "*)__dtp_alloc(sizeof(" + ty + "))";
        }

        if (auto* n = dynamic_cast<const ArrayExpr*>(node)) {
            std::string s = "{";
            for (size_t i=0;i<n->elements.size();i++){
                s+=gen_expr(n->elements[i].get());
                if(i+1<n->elements.size()) s+=",";
            }
            return s+"}";
        }

        if (auto* n = dynamic_cast<const StructLitExpr*>(node)) {
            std::string s = "(" + n->name + "){";
            for (size_t i=0;i<n->fields.size();i++){
                s += "." + n->fields[i].first + "=" + gen_expr(n->fields[i].second.get());
                if(i+1<n->fields.size()) s+=",";
            }
            return s+"}";
        }

        if (auto* n = dynamic_cast<const IfExpr*>(node)) {
            // Ternary for simple cases
            std::string cond  = gen_expr(n->cond.get());
            std::string then_ = "0";
            std::string else_ = "0";
            if (auto* blk = dynamic_cast<const BlockExpr*>(n->then_block.get()))
                if (blk->tail_expr) then_ = gen_expr(blk->tail_expr.get());
            if (n->else_block)
                if (auto* blk = dynamic_cast<const BlockExpr*>(n->else_block.get()))
                    if (blk->tail_expr) else_ = gen_expr(blk->tail_expr.get());
            return "(" + cond + " ? " + then_ + " : " + else_ + ")";
        }

        if (auto* n = dynamic_cast<const RangeExpr*>(node)) {
            // Range as slice — lightweight representation
            return "(__dtp_slice){.ptr=0,.len=" + gen_expr(n->end.get()) +
                   "-.len=" + gen_expr(n->start.get()) + "}";
        }

        return "0 /* unknown expr */";
    }

    std::string infer_c_type(const ASTNode* node) {
        if (!node) return "i64";
        if (node->type) return gen_type(node->type.get());
        if (dynamic_cast<const LitIntExpr*>(node))   return "i64";
        if (dynamic_cast<const LitFloatExpr*>(node)) return "f64";
        if (dynamic_cast<const LitStrExpr*>(node))   return "const char*";
        if (dynamic_cast<const LitBoolExpr*>(node))  return "bool";
        if (dynamic_cast<const LitCharExpr*>(node))  return "dtp_char";
        return "i64";
    }
};

} // namespace dtp
